name: Build c-api

on:
  push:
    branches: [ master ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup i686-pc-windows-msvc
      run: rustup target add i686-pc-windows-msvc
    - name: Build
      run: |
        cargo build --release -p c-api
        cargo build --release --target=i686-pc-windows-msvc -p c-api
        cargo build --release --target=x86_64-pc-windows-msvc -p c-api
    - name: Artifact (win64)
      uses: actions/upload-artifact@v2
      with:
        name: win64
        path: target/x86_64-pc-windows-msvc/release/cold_clear.dll
    - name: Artifact (win32)
      uses: actions/upload-artifact@v2
      with:
        name: win32
        path: target/i686-pc-windows-msvc/release/cold_clear.dll
